swagger: "2.0"
info:
  title: Argent Bank Transaction API
  description: API model proposal for user transactions
  version: 2.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Transactions Current Month API
      description: API for fetching current month transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User transactions retrieved successfully
          schema:
            $ref: "#/definitions/allTransactionsResponse"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Transactions not found
        "500":
          description: Internal Server Error
  /user/transaction/{idTransaction}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Transaction Show API
      description: API for showing a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: idTransaction
          description: Id of the transaction
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction retrieved successfully
          schema:
            $ref: "#/definitions/ApiTransactionResponse"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Transaction Edit API
      description: API for updating a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: idTransaction
          description: Id of the transaction that needs to be edited
          required: true
          type: string
        - in: body
          name: body
          description: Edit transaction
          required: true
          schema:
            $ref: "#/definitions/editTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction edited successfully
          schema:
            $ref: "#/definitions/ApiTransactionResponse"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  allTransactionsResponse:
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/transaction'
  ApiTransactionResponse:
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          date:
            type: string
          amount:
            type: number
          description:
            type: string
          category:
            type: string
          notes:
            type: string
  transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
      amount:
        type: number
      description:
        type: string
      category:
        type: string
      notes:
        type: string
  editTransaction:
    properties:
      category:
        type: string
      notes:
        type: string